version: "3.8"
services:
  app:
    environment:
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      MONGO_ATLAS_URL: "${MONGO_ATLAS_URL}"
      MONGO_DATABASE: "${MONGO_DATABASE}"
    build: ./app
    ports:
      - "4567:4567"
    volumes:
      - ./app:/app
  frontend:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks: 
  internal-network:
    driver: bridge
    name: cruddur